# Generated by Django 5.1.4 on 2024-12-11 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0002_contact_remove_visitor_departments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="contact",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="visitors.contact",
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="meeting_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visitor",
            name="meeting_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visitor",
            name="status",
            field=models.CharField(
                choices=[
                    ("Scheduled", "Scheduled"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Scheduled",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=20,
            ),
        ),
    ]
